-- game.ReplicatedStorage.Module.Guide.Step_NotUse.GuideStep_11_OpenToolStore
-- game.ReplicatedStorage.ScriptAlias.GuideStep_11_OpenToolStore
local GuideStep_11_OpenToolStore = require(game.ReplicatedStorage.Module.Guide.Step_NotUse.GuideStep_11_OpenToolStore)
return GuideStep_11_OpenToolStore